name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1

      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Generate
        run: nr generate

      - name: Cleanup
        run: |
          rm -rf node_modules
          rm -rf dist

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: rfe
          entrypoint: serve.ts
